### ISSUE TITLE
+-Zeichen geht bei HTML-Generierung verloren

### ISSUE THREAD

**Issue by olivergrimm** [geostandards-ch/doc_refhb24#2]
Im Kapitel https://geostandards-ch.github.io/doc_refhb24/#_ausdr%C3%BCcke ist mir aufgefallen, dass das +-Zeichen in den Erläuterungen verloren geht.

**Comment by beistehen** [comment]
Korrektur:
![grafik](https://github.com/geostandards-ch/doc_refhb24/assets/26199857/a3ab62c4-b4ec-48b8-9447-e107d74b1f0f)
