### ISSUE TITLE
Grammar file for download

### ISSUE THREAD

**Issue by pjanck** [geostandards-ch/doc_refhb24#6]
Looking through the documentation, there are multiple snippets of a grammar. 

Is there a complete grammar as a downloadable file accessible somewhere?

If yes: can you please point me to it?

If no: is it planned to have it online in the future?

**Comment by beistehen** [comment]
Have a look at this folder:
https://github.com/claeis/ili2c/tree/master/ili2c-core/src/main/antlr/ch/interlis/ili2c/parser

(but it looks like the grammar file for INTERLIS 2.4 is missing. @Philippluca any hints where to find it?)

**Comment by Philippluca** [comment]
@beistehen The files in the mentioned folder you refer to are in a `.txt`. They are more than likely to be a manual extract from the Reference Handbooks according to their first line:
> according to refman 2005-06-16 with corrections by ce

For the ili2c tool itself only the Antler-Grammers `*.g`-Files are of relevance.

**Comment by pjanck** [comment]
@beistehen @Philippluca Thank you for the answers. 

Is there a plan to have INTERLIS 2.4 as an ANTLR `.g4` file (even if in a `.txt` format) available sometime soon? I could reconstruct it from 2.3 and pull request it, if there is a list of changes available somewhere to study.

**Comment by beistehen** [comment]
@pjanck I am not aware of plans to change the antlr version used in INTERLIS compiler (ili2c). But there is an abandoned project to write a compiler in C++. In [its](https://github.com/infogrips/ilic/tree/main/source/input/parser/grammar/other) repo you will find some grammar files, although I have no information about the completeness of the files.

**Comment by pjanck** [comment]
@beistehen The repo helps a lot! 

Also: I am not asking about a version update of the grammar files, but rather for the grammar file of INTERLIS 2.4 - as noted by yourself above, it is missing. Thus: is there a list of changes from 2.3 to 2.4 to reconstruct the grammar by myself?

**Comment by beistehen** [comment]
> Thus: is there a list of changes from 2.3 to 2.4 to reconstruct the grammar by myself?

On a technical level you might want to compare the two grammar files [interlis23.g](https://github.com/claeis/ili2c/blob/master/ili2c-core/src/main/antlr/ch/interlis/ili2c/parser/interlis23.g) and [interlis24.g](https://github.com/claeis/ili2c/blob/master/ili2c-core/src/main/antlr/ch/interlis/ili2c/parser/interlis24.g) (both in ANTLR2 I guess).

On a general level you might want to compare the two reference manuals [INTERLIS 2.3 (german)](https://www.interlis.ch/download/interlis2/ili2-refman_2006-04-13_d.pdf) and [INTERLIS 2.4 (german)](https://ech.ch/sites/default/files/dosvers/hauptdokument/STAN_d_DEF_2017-10-27_eCH-0031_V2.0_INTERLIS_2-Referenzhandbuch.pdf).

It looks like there is no plain text file like [syntax23.txt](https://github.com/claeis/ili2c/blob/master/ili2c-core/src/main/antlr/ch/interlis/ili2c/parser/syntax23.txt) for INTERLIS 2.4 as it is probably not needed for the development of the software.

What is your use case to reconstruct the grammar in a separate text file?
